name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      MIX_ENV: test

    name: Elixir ${{ matrix.pair.elixir }} / OTP ${{ matrix.pair.otp }}

    strategy:
      matrix:
        elixir: [1.12.3]
        otp: [24.0.6]

    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install minimal stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Dependencies
        run: mix deps.get

      - run: mix format --check-formatted

      - run: mix deps.unlock --check-unused

      - run: HUMAN_NAME_BUILD=1 mix deps.compile

      - run: HUMAN_NAME_BUILD=1 mix compile --warnings-as-errors

      - name: Run Tests
        run: HUMAN_NAME_BUILD=1 mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
